### PR TITLE
Throw custom field options when exposing rules

### PR DESCRIPTION
**Pull request by bibendi**
Hey @palkan! :cat: 

I need custom field's options when exposing policy rules.

### CODE REVIEW

**Comment by palkan** [comment]
Nice addition.

Can we add at least one test to make sure we won't break this functionality in the future?

**Comment by bibendi** [comment]
Okay, I'll try to add it on holydays

**Comment by palkan** [comment]
Closed via https://github.com/palkan/action_policy-graphql/commit/bae4f59035d0f7e02c501423067272f5f1ca7d05

**Comment by bibendi** [comment]
Oh, damn, I forgot about it! It was the new year :)

**Pull request closed without merging**
